web:
  build: docker-nginx-php
  ports:
    - "8000:80"
  links:
    - db
  volumes:
    - ./code:/var/www
    - ./conf/nginx/conf.d:/etc/nginx/conf.d
    - ./log/nginx:/var/log/nginx
    - ./log/php-fpm:/var/log/php-fpm
dbdata:
  build: docker-mysql-data
db:
  build: docker-mysql
  ports:
    - "3306:3306"
  volumes:
    - ./log/mysql:/var/log/mysql
  volumes_from:
    - dbdata
